# Use the official Alpine base image
FROM alpine:latest

# Install necessary packages
RUN apk update && apk add --no-cache \
    nginx \
    php \
    php-fpm \
    dnsmasq \
    supervisor

# Copy configuration files
COPY nginx.conf /etc/nginx/nginx.conf
#COPY nginx-selfsigned.key /etc/nginx/certs/nginx-selfsigned.key
#COPY nginx-selfsigned.crt /etc/nginx/certs/nginx-selfsigned.crt
COPY privkey.pem /etc/nginx/certs/privkey.pem
COPY fullchain.pem /etc/nginx/certs/fullchain.pem
COPY php.ini /etc/php8/php.ini
COPY supervisord.conf /etc/supervisord.conf
COPY dnsmasq.conf /etc/dnsmasq.conf
COPY index.php /var/www/html/
COPY cascade.css /var/www/html/
COPY favicon.ico /var/www/html/
COPY favicon.png /var/www/html/
COPY logo.png /var/www/html/
COPY GalanoGrotesqueW00-Regular.woff2 /var/www/html/
COPY spinner.svg /var/www/html/
COPY android-chrome-512x512.png /var/www/html/
COPY android-chrome-icon.png /var/www/html/
COPY apple-touch-icon.png /var/www/html/

# Expose ports
EXPOSE 80 443 53/udp

# Start services using Supervisor
CMD ["/usr/bin/supervisord", "-c", "/etc/supervisord.conf"]