#!/bin/sh /etc/rc.common

START=99
STOP=01
USE_PROCD=1

start_service() {
    procd_open_instance
    procd_set_param command /usr/bin/docker-checker.sh
    procd_set_param pidfile /var/run/docker-checker.pid
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_set_param respawn ${respawn_threshold:-3600} ${respawn_timeout:-5} ${respawn_retry:-5}
    procd_close_instance
}

stop_service() {
    local pid
    if [ -f /var/run/docker-checker.pid ]; then
        pid=$(cat /var/run/docker-checker.pid)
        kill $pid
        rm -f /var/run/docker-checker.pid
    fi
}

reload_service() {
    stop
    start
}